# PRO TIP : Test your modifications locally with:
## $ gitlab-ci-multi-runner exec docker {name_of_the_job}


variables:
    PGDATA: /var/lib/postgresql/data
    PGUSER: postgres    
    EXTDIR: /usr/share/postgresql/10/extension/

image: postgres:10

before_script:
    - mkdir -p $PGDATA
    - mkdir -p $EXTDIR                                                                                                                                 
    - chown postgres $PGDATA                                                                                                                           
    - gosu postgres initdb                                                                                                                             
    - gosu postgres pg_ctl start  

make:
  stage: build    
  script:
    - apt-get update && apt-get install -y make postgresql-server-dev-10
    - make extension
    - make install 
    - make installcheck
  artifacts:
    paths:
        - anon*
        - results/
    expire_in: 1 day
    
