PostgreSQL:
  image: registry.gitlab.com/dalibo/postgresql_anonymizer
  ports:
    - "54322:5432"
  environment:
    - POSTGRES_PASSWORD=CHANGEME
    - PGUSER=postgres # required for `make installcheck`
  command: postgres -c shared_preload_libraries='anon'
  working_dir: /tmp/source
  volumes:
    - $PWD:/tmp/source
    #- $PWD/anon:/usr/share/postgresql/10/extension/anon
